name: dopamine-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - astroid=2.2.5=py36_0
  - autopep8=1.4.4=py_0
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - isort=4.3.16=py36_0
  - lazy-object-proxy=1.3.1=py36h14c3975_1000
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mccabe=0.6.1=py_1
  - ncurses=6.1=hf484d3e_1002
  - openssl=1.1.1b=h14c3975_1
  - pip=19.0.3=py36_0
  - pycodestyle=2.5.0=py_0
  - pylint=2.3.1=py36_0
  - python=3.6.7=h381d211_1004
  - readline=7.0=hf8c457e_1001
  - setuptools=40.8.0=py36_0
  - sqlite=3.26.0=h67949de_1001
  - tk=8.6.9=h84994c4_1001
  - typed-ast=1.3.1=py36h14c3975_0
  - wheel=0.33.1=py36_0
  - wrapt=1.11.1=py36h14c3975_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - pip:
    - absl-py==0.7.1
    - astor==0.7.1
    - atari-py==0.1.7
    - chardet==3.0.4
    - enum34==1.1.6
    - future==0.17.1
    - gast==0.2.2
    - gin-config==0.1.4
    - grpcio==1.19.0
    - gym==0.12.1
    - h5py==2.9.0
    - idna==2.8
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.1
    - mock==2.0.0
    - numpy==1.16.2
    - opencv-python==4.0.0.21
    - pbr==5.1.3
    - protobuf==3.7.1
    - pyglet==1.3.2
    - requests==2.21.0
    - scipy==1.2.1
    - six==1.12.0
    - tensorboard==1.13.1
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - urllib3==1.24.1
    - werkzeug==0.15.1

