name: ray-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.7.1=py36_0
  - astor=0.7.1=py_0
  - astroid=2.2.5=py36_0
  - autopep8=1.4.4=py_0
  - c-ares=1.15.0=h14c3975_1001
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - gast=0.2.2=py_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - isort=4.3.16=py36_0
  - lazy-object-proxy=1.3.1=py36h14c3975_1000
  - libblas=3.8.0=4_openblas
  - libcblas=3.8.0=4_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libprotobuf=3.7.0=h8b12597_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - markdown=2.6.11=py_0
  - mccabe=0.6.1=py_1
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.2=py36h7fc5cc3_0
  - openblas=0.3.5=ha44fe06_0
  - openssl=1.1.1b=h14c3975_1
  - pip=19.0.3=py36_0
  - protobuf=3.7.0=py36he1b5a44_1
  - pycodestyle=2.5.0=py_0
  - pylint=2.3.1=py36_0
  - python=3.6.7=h381d211_1004
  - readline=7.0=hf8c457e_1001
  - setuptools=40.8.0=py36_0
  - sqlite=3.26.0=h67949de_1001
  - tensorboard=1.10.0=py36_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - tk=8.6.9=h84994c4_1001
  - typed-ast=1.3.1=py36h14c3975_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py36_0
  - wrapt=1.11.1=py36h14c3975_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h14c3975_1004
  - pip:
    - atari-py==0.1.7
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - filelock==3.0.10
    - flatbuffers==1.10
    - funcsigs==1.0.2
    - future==0.17.1
    - gym==0.12.1
    - idna==2.8
    - lz4==2.1.6
    - more-itertools==7.0.0
    - opencv-python-headless==4.0.0.21
    - pillow==6.0.0
    - pluggy==0.9.0
    - psutil==5.6.1
    - py==1.8.0
    - py-spy==0.1.10
    - pyglet==1.3.2
    - pyopengl==3.1.0
    - pytest==4.4.0
    - pyyaml==5.1
    - redis==3.2.1
    - requests==2.21.0
    - scipy==1.2.1
    - setproctitle==1.1.10
    - six==1.12.0
    - typing==3.6.6
    - urllib3==1.24.1

